[platformio]
default_envs = stackchan-cores3

[env:stackchan-cores3]
platform = platformio/espressif32@6.7.0
board = m5stack-cores3
framework = arduino

board_microros_transport = serial
board_microros_distro = jazzy

monitor_speed = 115200
build_flags =
    -D STACKCHAN_DEVICE_ID=\"default\"
    -D STACKCHAN_MICROROS_SERIAL_BAUD=115200

lib_deps =
    https://github.com/m5stack/StackChan-BSP.git#1.1.0
    https://github.com/micro-ROS/micro_ros_platformio.git#de7a61c
